### ISSUE TITLE
ImportError: cannot import name 'SOMFactory'

### ISSUE THREAD

**Issue by stef8310** [sevamoo/SOMPY#36]
Hello,

I have installed sompy without any errors (https://github.com/sevamoo/SOMPY).
However when i try:

import sompy

I receive an error code:

File "C:\Anaconda3\lib\site-packages\sompy-1.0-py3.5.egg\sompy\__init__.py", line 30, in <module>
 from sompy import SOMFactory
ImportError: cannot import name 'SOMFactory'

I am using Python 3.5.1 (Anaconda 4.1.1 for Windows)
Any help or suggestions would be greatly appreciated.

Stefan

**Comment by sevamoo** [comment]
Hi 
Unfortunately, python 3 is not fully compatible yet. 
This might be the reason.

**Comment by Akshaysehgal2005** [comment]
Python 3 isnt the issue here. The direct pip install is not updated and doesnt include SOMFactory with used (atleast for me). I had to download the setup and used the suggested method of installation.

python setup.py install

But, (again for me only) instead of installing it, it created a .egg file in my site-packages folder. So I had to use pip on the local zip folder containing the setup to directly install it. 

I also ran into the ipdb conflict after that but it was already resolved by Sevamoo in another thread I think (downgrading it to 0.8.1)

**Comment by Clarahi** [comment]
Hello all!
I am trying to install SOMpy and I have the exact error as @Akshaysehgal2005. I am working in a virtualenv with python 2.7. I ran python setup.py install, everything seems to be well but then when I run the example:  'module' object has no attribute 'SOMFactory'

could you clarify what did you do exactly when you say: " I had to use pip on the local zip folder containing the setup to directly install it."

I would very much appreciate it.

thanks! can't wait to use this tool. I used to use the library in matlab in my phd  but now I would like to move to python.

thanks!!

**Comment by Clarahi** [comment]
I solved it. These were my steps if anyone has the same problem.
Downloaded the zip: https://github.com/sevamoo/SOMPY/archive/master.zip
and run:
>pip install SOMPY-master.zip
Then I had to install ipdb:
>pip install ipdb
And dowgrade it:
>pip install ipdb==0.8.1

And now it works!!

**Comment by Ali11000000** [comment]
install V1.0.0 via :  pip3 install git+https://github.com/compmonks/SOMPY.git
change ipdb version to  pip install ipdb==0.8.1
now it works!!

**Comment by dnsan** [comment]
Hello, I'd followed your instruction but still get error. Using python 3.79 now. Have I to downgrade to 3.5 ?
